### ISSUE TITLE
Linux support for latest Pascal improvements?

### ISSUE THREAD

**Issue by ddobreff** [KlausT/ccminer-cryptonight#11]
Hello,
I experience a problem compiling latest Pascal improvements on Ubuntu 16.04.
Any help appreciated.
-------------------------------------------------------------------------------------------
make
all-recursive
make[1]: Entering directory '/home/undead/Build/ccminer-cryptonight'
Making all in compat
make[2]: Entering directory '/home/undead/Build/ccminer-cryptonight/compat'
make[3]: Entering directory '/home/undead/Build/ccminer-cryptonight/compat'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/undead/Build/ccminer-cryptonight/compat'
make[2]: Leaving directory '/home/undead/Build/ccminer-cryptonight/compat'
make[2]: Entering directory '/home/undead/Build/ccminer-cryptonight'
gcc -DHAVE_CONFIG_H -I.  -I/usr/local/cuda/include -msse2  -fopenmp -pthread -fno-strict-aliasing  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-cpu-miner.o -MD -MP -MF .deps/ccminer-cpu-miner.Tpo -c -o ccminer-cpu-miner.o `test -f 'cpu-miner.c' || echo './'`cpu-miner.c
mv -f .deps/ccminer-cpu-miner.Tpo .deps/ccminer-cpu-miner.Po
gcc -DHAVE_CONFIG_H -I.  -I/usr/local/cuda/include -msse2  -fopenmp -pthread -fno-strict-aliasing  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-util.o -MD -MP -MF .deps/ccminer-util.Tpo -c -o ccminer-util.o `test -f 'util.c' || echo './'`util.c
mv -f .deps/ccminer-util.Tpo .deps/ccminer-util.Po
gcc -DHAVE_CONFIG_H -I.  -I/usr/local/cuda/include -msse2  -fopenmp -pthread -fno-strict-aliasing  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-sha2.o -MD -MP -MF .deps/ccminer-sha2.Tpo -c -o ccminer-sha2.o `test -f 'sha2.c' || echo './'`sha2.c
mv -f .deps/ccminer-sha2.Tpo .deps/ccminer-sha2.Po
nvcc -g -O2 -I . -D_FORCE_INLINES -I/usr/local/cuda/include -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_53,code=\"sm_53,compute_53\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_62,code=\"sm_62,compute_62\" --maxrregcount=128 --ptxas-options=-v  -o cryptonight/cryptonight.o -c cryptonight/cryptonight.cu
ptxas info    : 0 bytes gmem
ptxas info    : 0 bytes gmem
ptxas info    : 0 bytes gmem
ptxas info    : 0 bytes gmem
ptxas info    : 0 bytes gmem
nvcc -g -O2 -I . -D_FORCE_INLINES -I/usr/local/cuda/include -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_53,code=\"sm_53,compute_53\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_62,code=\"sm_62,compute_62\" --maxrregcount=128 --ptxas-options=-v  -o cryptonight/cuda_cryptonight_core.o -c cryptonight/cuda_cryptonight_core.cu
cryptonight/cuda_cryptonight_core.cu(50): error: expected an identifier

cryptonight/cuda_cryptonight_core.cu(50): error: inline specifier allowed on function declarations only

cryptonight/cuda_cryptonight_core.cu(50): warning: attribute "always_inline" does not apply here

cryptonight/cuda_cryptonight_core.cu(50): error: incomplete type is not allowed

cryptonight/cuda_cryptonight_core.cu(50): warning: list initialization syntax is a C++11 feature

cryptonight/cuda_cryptonight_core.cu(50): error: type name is not allowed

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ","

cryptonight/cuda_cryptonight_core.cu(50): error: identifier "lo" is undefined

cryptonight/cuda_cryptonight_core.cu(50): error: expected an expression

cryptonight/cuda_cryptonight_core.cu(50): error: type name is not allowed

cryptonight/cuda_cryptonight_core.cu(50): error: expected an expression

cryptonight/cuda_cryptonight_core.cu(50): error: identifier "hi" is undefined

cryptonight/cuda_cryptonight_core.cu(50): error: type name is not allowed

cryptonight/cuda_cryptonight_core.cu(50): error: expected an expression

cryptonight/cuda_cryptonight_core.cu(50): error: expected a "}"

cryptonight/cuda_cryptonight_core.cu(50): error: this declaration has no storage class or type specifier

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ";"

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: this declaration has no storage class or type specifier

cryptonight/cuda_cryptonight_core.cu(50): error: "uint64_t" has already been declared in the current scope

cryptonight/cuda_cryptonight_core.cu(50): error: expected an expression

cryptonight/cuda_cryptonight_core.cu(50): error: expression must have arithmetic or enum type

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: this declaration has no storage class or type specifier

cryptonight/cuda_cryptonight_core.cu(50): error: variable "uint64_t" has already been defined

cryptonight/cuda_cryptonight_core.cu(50): error: expected an expression

cryptonight/cuda_cryptonight_core.cu(50): error: expression must have arithmetic or enum type

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: this declaration has no storage class or type specifier

cryptonight/cuda_cryptonight_core.cu(50): error: variable "uint64_t" has already been defined

cryptonight/cuda_cryptonight_core.cu(50): error: a value of type "int" cannot be used to initialize an entity of type "int [0]"

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: expected a ")"

cryptonight/cuda_cryptonight_core.cu(50): error: this declaration has no storage class or type specifier

cryptonight/cuda_cryptonight_core.cu(50): error: variable "uint64_t" has already been defined

cryptonight/cuda_cryptonight_core.cu(50): error: expected a declaration

cryptonight/cuda_cryptonight_core.cu(184): warning: parsing restarts here after previous syntax error

cryptonight/cuda_cryptonight_core.cu(186): error: this declaration has no storage class or type specifier

cryptonight/cuda_cryptonight_core.cu(186): error: identifier "ctx_a" is undefined

cryptonight/cuda_cryptonight_core.cu(187): error: this declaration has no storage class or type specifier

cryptonight/cuda_cryptonight_core.cu(187): error: variable "a" has already been defined

cryptonight/cuda_cryptonight_core.cu(188): error: this declaration has no storage class or type specifier

cryptonight/cuda_cryptonight_core.cu(188): error: identifier "ctx_b" is undefined

cryptonight/cuda_cryptonight_core.cu(189): error: this declaration has no storage class or type specifier

cryptonight/cuda_cryptonight_core.cu(189): error: variable "b" has already been defined

cryptonight/cuda_cryptonight_core.cu(191): error: expected a declaration

cryptonight/cuda_cryptonight_core.cu(233): warning: this pragma must immediately precede a statement

cryptonight/cuda_cryptonight_core.cu(237): warning: parsing restarts here after previous syntax error

cryptonight/cuda_cryptonight_core.cu(238): error: expected a declaration

cryptonight/cuda_cryptonight_core.cu(241): error: expected a declaration

At end of source: warning: parsing restarts here after previous syntax error

50 errors detected in the compilation of "/tmp/tmpxft_00001902_00000000-15_cuda_cryptonight_core.compute_62.cpp1.ii".
Makefile:1152: recipe for target 'cryptonight/cuda_cryptonight_core.o' failed
make[2]: *** [cryptonight/cuda_cryptonight_core.o] Error 2
make[2]: Leaving directory '/home/undead/Build/ccminer-cryptonight'
Makefile:726: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/undead/Build/ccminer-cryptonight'
Makefile:396: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by KlausT** [comment]
Sometimes there are problems when you are using incompatible versions of gcc and CUDA.
Maybe that's the case here.
Other than that I have no idea why it doesn't work.

**Comment by ddobreff** [comment]
Cuda is 8.0.44 using latest ubuntu 16.04

**Comment by KlausT** [comment]
Looks like the same issue as this:
[](https://github.com/KlausT/ccminer-cryptonight/issues/13)
