### ISSUE TITLE
2.00 make error

### ISSUE THREAD

**Issue by werdwerdus** [KlausT/ccminer-cryptonight#14]
ubuntu 16.04 x64
nvcc 8.0.44
gcc 5.4.0

./configure ran successfully 

ran `make` and received this error:

> drew@drew-miner:~/ccminer/ccminer-cryptonight-2.00$ make
make  all-recursive
make[1]: Entering directory '/home/drew/ccminer/ccminer-cryptonight-2.00'
Making all in compat
make[2]: Entering directory '/home/drew/ccminer/ccminer-cryptonight-2.00/compat'
Making all in jansson
make[3]: Entering directory '/home/drew/ccminer/ccminer-cryptonight-2.00/compat/jansson'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/drew/ccminer/ccminer-cryptonight-2.00/compat/jansson'
make[3]: Entering directory '/home/drew/ccminer/ccminer-cryptonight-2.00/compat'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/drew/ccminer/ccminer-cryptonight-2.00/compat'
make[2]: Leaving directory '/home/drew/ccminer/ccminer-cryptonight-2.00/compat'
make[2]: Entering directory '/home/drew/ccminer/ccminer-cryptonight-2.00'
make[2]: *** No rule to make target 'sph/bmw.c', needed by 'ccminer-bmw.o'.  Stop.
make[2]: Leaving directory '/home/drew/ccminer/ccminer-cryptonight-2.00'
Makefile:744: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/drew/ccminer/ccminer-cryptonight-2.00'
Makefile:305: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by deshi-basara** [comment]
Did you forget to execute `./autogen.sh` before configure & make?

**Comment by werdwerdus** [comment]
yep.. thanks. i compiled 1.03 when it was release and i guess i forgot that this time around. i'll remember to read the install instructions next time.
