### ISSUE TITLE
Api port?

### ISSUE THREAD

**Issue by lyolyalya** [KlausT/ccminer-cryptonight#15]
hey.seems like your miner hasn't api port?or maybe it is not 4068 by default?if it so - tell us which port to use,please?if not - are you planing to add this option in the near future?
thanks.

**Comment by KlausT** [comment]
I have not decided yet if I will add it or not.

**Comment by lyolyalya** [comment]
would be nice=)

**Comment by KlausT** [comment]
Epsylon3 (tpruvot) is working on adding cryptonight to his ccminer.
https://github.com/tpruvot/ccminer/tree/xmr-dev
Maybe you can try that miner when it is ready:

**Comment by lyolyalya** [comment]
it's a pitty...your miner gives mush better results now...ok.will wait...
