### ISSUE TITLE
error while loading shared libraries: libcudart.so.8.0

### ISSUE THREAD

**Issue by crypdick** [KlausT/ccminer-cryptonight#18]
When I run ccminer I get the following error:

`ccminer: error while loading shared libraries: libcudart.so.8.0: cannot open shared object file: No such file or directory`

I'm not an expert on compiling, but it looks to me like I have version 6.5.19:
```
richard@motherload:~/Apps/ccminer-cryptonight$ locate libcudart
/usr/lib/libcudart.so
/usr/local/cuda-6.5/doc/man/man7/libcudart.7
/usr/local/cuda-6.5/doc/man/man7/libcudart.so.7
/usr/local/cuda-6.5/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-6.5/targets/x86_64-linux/lib/libcudart.so.6.5
/usr/local/cuda-6.5/targets/x86_64-linux/lib/libcudart.so.6.5.19
/usr/local/cuda-6.5/targets/x86_64-linux/lib/libcudart_static.a
```

(`/usr/lib/libcudart.so` is a symbolic link to `/usr/local/cuda-6.5/targets/x86_64-linux/lib/libcudart.so.6.5.19`)

**Comment by KlausT** [comment]
I have no idea why it tries to link to link a 8.0 lib when you have cuda 6.5.
Maybe try to install cuda 8.0 ?

**Comment by crypdick** [comment]
Ok, done. Now I'm getting this error:

```
richard@motherload:~/Apps/ccminer-cryptonight$ ccminer -o stratum+tcp://monerohash.com:3333 -u 49rGPcgztcd3ULhDSiao7AZh3666xfE3LTTWwUHXeqyJ37TmvtCWtcsCRqRs794HnKT3exyvoZ6hFTYgB3CD4x7y8dXH2Xg -p x
    *** ccminer-cryptonight for nVidia GPUs by tsiv ***
 based on ccMiner by Christian Buchner and Christian H.
 based on cpuminer-multi by LucasJones
 based on pooler-cpuminer 2.3.2 (c) 2010 Jeff Garzik, 2012 pooler
    BTC donation address: 1JHDKp59t1RhHFXsTw2UQpR3F9BBz3R3cs
    DRK donation address: XrHp267JNTVdw5P3dsBpqYfgTpWnzoESPQ
    JPC donation address: Jb9hFeBgakCXvM5u27rTZoYR9j13JGmuc2
    VTC donation address: VwYsZFPb6KMeWuP4voiS9H1kqxcU9kGbsw
    XMR donation address: 
      (man these are long... single address, split on two lines)
      42uasNqYPnSaG3TwRtTeVbQ4aRY3n9jY6VXX3mfgerWt4ohD
      QLVaBPv3cYGKDXasTUVuLvhxetcuS16ynt85czQ48mbSrWX
-----------------------------------------------------------------
*** stack smashing detected ***: ccminer terminated
Aborted (core dumped)
```

My video card is a GeForce GTX 580 (CUDA compute 2.0). I have the latest drivers installed from Nvidia. I have tried to use the --threads=1 flag to see if that would help, but no dice. I am out of ideas.

**Comment by KlausT** [comment]
I don't think that this is my version of ccminer-cryptonight.

**Comment by crypdick** [comment]
I think you may be right! I was sure I was running yours because I was running the command inside your cloned repo directory, but now that I've checked `which ccminer` I see that it lives in `/usr/local/bin/ccminer`. It's probably the ancient tsiv version. 

How should I uninstall ccminer?`sudo rm`?

**Comment by KlausT** [comment]
Yes

**Comment by crypdick** [comment]
That was the problem. Everything is working. Thanks!
