### ISSUE TITLE
Application name is typo

### ISSUE THREAD

**Issue by denneko223355** [KlausT/ccminer-cryptonight#28]
I deployed Ver 2.02 zip, but got an error.
After checking, the application name was "ccminer-**cryto**night.exe".
I replaced it and changed it to "ccminer-**crypto**night.exe", it started to work normally.
＝Original text（原文）＝
Ver2.02のzipを展開した所、エラーが出て動きませんでした。
確認したところ、アプリケーション名が"ccminer-crytonight.exe"になっていて、pが抜けてました。
pを入れ直し、"ccminer-cryptonight.exe"にしたところ、正常に動くようになりました。

**Comment by whardier** [comment]
yeh.. I don't want to Cry Tonight.

**Comment by KlausT** [comment]
should be fixed with version 2.03
