### ISSUE TITLE
incomplete download?

### ISSUE THREAD

**Issue by Bullseye161** [KlausT/ccminer-cryptonight#29]
Downloaded the CCminer the latest version and in the download files all that was there was " ccminer-cryptonight, License, and readme," downloaded the Cudart 64_80.dll after I got that Error. Now when I try to launch the program it just crashes. Found 3 videos on it and there downloads seem to have another Dll file and another application file.

**Comment by KlausT** [comment]
Same issue as this:
https://github.com/KlausT/ccminer-cryptonight/issues/27

**Comment by KlausT** [comment]
please try version 2.03
