### ISSUE TITLE
Undefined reference to `jsonp_dtostr'

### ISSUE THREAD

**Issue by Megavolv** [KlausT/ccminer-cryptonight#39]
I see these errors when run make.

compat/jansson/libjansson.a(dump.o): In function `do_dump':
/home/user/ccminer-cryptonight/compat/jansson/dump.c:210: undefined reference to `jsonp_dtostr'
compat/jansson/libjansson.a(load.o): In function `lex_scan_number':
/home/user/ccminer-cryptonight/compat/jansson/load.c:555: undefined reference to `jsonp_strtod'
compat/jansson/libjansson.a(load.o): In function `parse_value':
/home/user/ccminer-cryptonight/compat/jansson/load.c:797: undefined reference to `jsonp_strtod'

Can you help me?

Thank you!

**Comment by KlausT** [comment]
I don't use Linux, so I have to make guesses here.
Did you run
./autogen.sh
./configure
before you run make?

**Comment by Megavolv** [comment]
Yes, of course.

**Comment by KlausT** [comment]
When libjansson-dev is installed then make should ignore the jansson files.
I will have to check what happened with jsonp_dtostr. Under Windows there's no problem with those files.

**Comment by Megavolv** [comment]
libjansson-dev wasn't installed. Now compile is ok.
