### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Gingeropolous** [KlausT/ccminer-cryptonight#5]
whar version of CUDA is this for?

gbone@gbone-therock:~/klaust_ccminer$ make
make  all-recursive
make[1]: Entering directory `/home/gbone/klaust_ccminer'
Making all in compat
make[2]: Entering directory `/home/gbone/klaust_ccminer/compat'
make[3]: Entering directory `/home/gbone/klaust_ccminer/compat'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/home/gbone/klaust_ccminer/compat'
make[2]: Leaving directory `/home/gbone/klaust_ccminer/compat'
make[2]: Entering directory `/home/gbone/klaust_ccminer'
gcc -std=gnu99 -DHAVE_CONFIG_H -I.  -D_FORCE_INLINES -msse2  -fopenmp -pthread -fno-strict-aliasing  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-cpu-miner.o -MD -MP -MF .deps/ccminer-cpu-miner.Tpo -c -o ccminer-cpu-miner.o `test -f 'cpu-miner.c' || echo './'`cpu-miner.c
cpu-miner.c:1609:6: error: conflicting types for ‘parse_device_config’
 void parse_device_config(int device, char *config, int *blocks, int *threads)
      ^
cpu-miner.c:66:6: note: previous declaration of ‘parse_device_config’ was here
 void parse_device_config(char *config, int *blocks, int *threads);
      ^
make[2]: *** [ccminer-cpu-miner.o] Error 1
make[2]: Leaving directory `/home/gbone/klaust_ccminer'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/gbone/klaust_ccminer'
make: *** [all] Error 2

**Comment by KlausT** [comment]
You get an error because there was a bug in the code.
For some reason it only affected compiling under Linux.

**Comment by Gingeropolous** [comment]
Just did a git pull, still can't compile..

ptxas info    : Compiling entry function '__cuda_dummy_entry__' for 'sm_35'
ptxas info    : Used 0 registers
ptxas warning : 'option -abi=no' might get deprecated in future
ptxas info    : 0 bytes gmem
ptxas warning : 'option -abi=no' might get deprecated in future
ptxas info    : 0 bytes gmem
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
Makefile:1152: recipe for target 'cryptonight/cryptonight.o' failed
make[2]: *** [cryptonight/cryptonight.o] Error 1
make[2]: Leaving directory '/home/cacna1c/klaus_ccminer'
Makefile:726: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/cacna1c/klaus_ccminer'
Makefile:396: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by KlausT** [comment]
That's because Nvidia doesn't support your gcc version. It works with older gcc versions.
I thought I had added a workaround for that, but it looks like I did something wrong.

**Comment by ZeroASIC** [comment]
If you look at the changes i made in my fork you'll notice that it's not a problem with the version of gcc, it's a problem with nvcc and you need to put the compiler option there, not gcc.
