### ISSUE TITLE
Wrong binaries in latest release 2.06

### ISSUE THREAD

**Issue by 7h3Cub3** [KlausT/ccminer-cryptonight#58]
Hello KlausT

It seems the latest release from 4days ago is in fact a old 2.0 build in cuda 8, the binaries released aren't cuda 9 and v2.06

`    *** ccminer-cryptonight 2.00 (64 bit) for nVidia GPUs by tsiv and KlausT
    *** Built with Visual Studio 2015 using the Nvidia CUDA Toolkit 8.0`

Could you please fix it ? thanks :)

**Comment by KlausT** [comment]
oops. :-)

**Comment by 7h3Cub3** [comment]
Nice, i'll be able to test it out :)

Cheers, and keep up the good work !
