### ISSUE TITLE
Mass solves after a dry spell

### ISSUE THREAD

**Issue by christiancoleman** [KlausT/ccminer-cryptonight#63]
![image](https://user-images.githubusercontent.com/6051308/34911239-76011ab6-f894-11e7-8954-be94b449a923.png)

I couldn't think of a better way to describe this, but the program will show both GPUs having a solid hash rate. And normally you'll have a 'yay!!!' sprinkled in every few lines. What I'm noticing happening sometimes after 5-8 hours of use the program will start to iterate between showing the GPUs for 20 lines and then all of a sudden show a ton of 'yay!!!'s. I'm checking my pool too and when this happens it's reporting a particularly low rate. What could be happening here? Bad connection to the pool or other?

**Comment by KlausT** [comment]
Maybe the pool is overloaded and/or broken.
With a bad connection you would see a red error message.

**Comment by christiancoleman** [comment]
Thanks for responding KlausT. I'm also seeing the following:

![image](https://user-images.githubusercontent.com/6051308/34911328-7f8b7750-f896-11e7-9ba5-999f57608e50.png)

I'm a programmer too. Which files should I take a look at to better understand what might be happening?

**Comment by KlausT** [comment]
If you want to take a look at the communication, then you could use the -P option.
Or you could use the --debug option for a little bit more details.

cpu-miner.c is the main file, which contains the miner_thread and the stratum_thread

**Comment by christiancoleman** [comment]
I think you may have been right about the pool. Just joined their forums and see another user experiencing something similar starting roughly 30 minutes ago. Also, my miner seems to have fixed itself. Never seen it do that without restarting. Anyways, thanks for the help. Should be able to close this.
