### ISSUE TITLE
Compiling error: No rule to make target 'sph/bmw.c'

### ISSUE THREAD

**Issue by deshi-basara** [KlausT/ccminer-cryptonight#7]
At first, thanks for reviving ccminer for cryptonight!

Since version 1.03 I'm getting the following error while compiling under (Arch)Linux:

> gcc -DHAVE_CONFIG_H -I.  -msse2  -fopenmp -pthread -fno-strict-aliasing  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-util.o -MD -MP -MF .deps/ccminer-util.Tpo -c -o ccminer-util.o `test -f 'util.c' || echo './'`util.c
> 
> mv -f .deps/ccminer-util.Tpo .deps/ccminer-util.Po
> 
> make[2]: *** Keine Regel vorhanden, um das Ziel „sph/bmw.c“,
>    benötigt von „ccminer-bmw.o“, zu erstellen.  Schluss.
> 
> make[2]: Verzeichnis „/.../.ccminer-cryptonight“ wird verlassen
> make[1]: *** [Makefile:744: all-recursive] Fehler 1
> make[1]: Verzeichnis „/.../.ccminer-cryptonight“ wird verlassen
> make: *** [Makefile:305: all] Fehler 2

**gcc:** 6.2.1
**cuda:** 7.5 and 8

I still can compile version 1.01 without problems.

**Comment by KlausT** [comment]
There is no bmw.c in ccminer-crytonight.
I think you have mixed the sources of two different projects

**Comment by deshi-basara** [comment]
Stupid me, forgot to execute the 'autogen.sh' ... everything is working fine with cuda 8 on Linux :+1:
